name: "Run tests for s390x architecture"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-24.04-s390x

    strategy:
      matrix:
        include:
          - name: "Python 3.14"
            python-version: '3.14'
            toxenv: 'py314'
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python ${{ matrix.python-version }}
        uses: ibm/setup-python-pz@main
        with:
          architecture: s390x
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install 'tox<4' tox-gh-actions flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          
      - name: Tests with tox
        env:
          TOXENV: ${{ matrix.toxenv }}
          COVERAGE_PROCESS_START: ""
        run: |
          tox
      - name: Linting
        if: ${{ matrix.python-version==3.12 }}
        env:
          TOXENV: lint
        run: |
          tox
      - name: Run Codecov
        if: ${{ matrix.python-version==3.12 }}
        env:
          TOXENV: lint
        run: |
          pip install codecov
          codecov
      - name: Upload coverage to Codecov
        if: ${{ matrix.python-version==3.12 }}
        uses: codecov/codecov-action@v5
